In [58]:
from torchwnn.datasets.iris import Iris
from torchwnn.classifiers import Wisard
from torchwnn.encoding import Thermometer
import pandas as pd

from os import listdir
from os.path import isfile  , join

In [59]:
iris=Iris()

display (type(iris.labels))

numpy.ndarray

In [ ]:
pasta_csv="../../../dataset"
n_classes=[]
for arquivo in sorted(listdir(pasta_csv),key=lambda s: (len(s), s)):
    file_path=join(pasta_csv, arquivo)
    if isfile(file_path) and ".csv" in arquivo:
        df=pd.read_csv(file_path)
        
        #retirando IPV6 e preparando IPV4 para int
        df = df[~df["src_ip"].str.contains(":", na=False)]
        df = df[~df["dst_ip"].str.contains(":", na=False)]
        df['src_ip']=df['src_ip'].str.replace('.','')
        df['dst_ip']=df['dst_ip'].str.replace('.','')
        
        n_classes= list(set(n_classes) | set(df['label'].unique().tolist()))
        features=df[["ts","src_ip","src_port","dst_ip","dst_port","duration","src_bytes","dst_bytes","missed_bytes","src_pkts","src_ip_bytes","dst_pkts","dst_ip_bytes"]].astype("float")
        labels=df[["label","type"]]
        
        features.to_pickle("./data/"+arquivo.replace(".csv",".pkl").replace("Network_dataset","feature"))
        labels.to_pickle("./data/"+arquivo.replace(".csv",".pkl").replace("Network_dataset","label"))
pd.DataFrame([len(n_classes)],columns=['n_classes']).to_pickle('./data/n_classes.pkl')
#pd.read_pickle("dados.pkl")


/tmp/ipykernel_387854/3583331683.py:6: DtypeWarning: Columns (0: src_bytes) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(file_path)
/tmp/ipykernel_387854/3583331683.py:6: DtypeWarning: Columns (0: src_bytes) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(file_path)


Descartar

In [ ]:
features = features[~features["src_ip"].str.contains(":", na=False)]
features = features[~features["dst_ip"].str.contains(":", na=False)]
features['src_ip']=features['src_ip'].str.replace('.','')
features['dst_ip']=features['dst_ip'].str.replace('.','')
#features['src_ip']=features['src_ip'].astype('int')
features.to_numpy()

array([[1556025780, '192168132', 36350, ..., 48, 1, 40],
       [1556025780, '192168130', 28550, ..., 48, 0, 0],
       [1556025780, '192168130', 26303, ..., 48, 0, 0],
       ...,
       [1556027414, '192168132', 57500, ..., 40, 0, 0],
       [1556027414, '192168132', 56927, ..., 44, 0, 0],
       [1556027414, '192168132', 38500, ..., 44, 1, 40]],
      shape=(999998, 13), dtype=object)

In [56]:
features.astype('float').to_numpy()

array([[1.55602578e+09, 1.92168132e+08, 3.63500000e+04, ...,
        4.80000000e+01, 1.00000000e+00, 4.00000000e+01],
       [1.55602578e+09, 1.92168130e+08, 2.85500000e+04, ...,
        4.80000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.55602578e+09, 1.92168130e+08, 2.63030000e+04, ...,
        4.80000000e+01, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.55602741e+09, 1.92168132e+08, 5.75000000e+04, ...,
        4.00000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.55602741e+09, 1.92168132e+08, 5.69270000e+04, ...,
        4.40000000e+01, 0.00000000e+00, 0.00000000e+00],
       [1.55602741e+09, 1.92168132e+08, 3.85000000e+04, ...,
        4.40000000e+01, 1.00000000e+00, 4.00000000e+01]],
      shape=(999998, 13))

In [79]:
n_classes=[]
n_classes= len(list(set(n_classes) | set(df['type'].unique().tolist())))
display(n_classes)

2

In [74]:
labels['label'].unique()

array([1, 0])